// <auto-generated />
namespace TimeSheet.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class permite_data_alteracao_nula : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(permite_data_alteracao_nula));
        
        string IMigrationMetadata.Id
        {
            get { return "201610090252146_permite_data_alteracao_nula"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
